version: '3.8'

services:
  webapp:
    container_name: translate-gemma-api
    build: .
    ports:
      - "6969:8000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /code/app
        - action: sync
          path: ./data
          target: /code/data
